# Lean, usage-driven MVP categories (marketplaces should be a tag, not a category)
- Транспорт/Такси
- Транспорт/Проезд
- Еда/Продукты
- Еда/Вне дома
- Дом/ЖКХ
- Дом/Быт
- Здоровье
- Одежда
- ИТ
- Развитие
- Развлечения
- Подарки
- Алкоголь и Табак
- Подписки
- Комиссии
- Прочее

