- name: Spotify
  amount: 199.00
  currency: RUB
  period: monthly
  next_charge: 2025-11-01

- name: DE-E1 Server
  amount: 300.00
  currency: RUB
  period: monthly
  next_charge: 2025-11-16

- name: Server 2
  amount: 730.00
  currency: RUB
  period: monthly
  next_charge: 2025-11-01
